### ISSUE TITLE
TRAPI 1.4 validation error: biolink:semmed_agreement_count not in Biolink

### ISSUE THREAD

**Issue by bill-baumgartner** [UCDenver-ccp/Translator-TM-Provider-Pipelines#72]
We need to request that the semmed_agreement_count edge attribute get added to Biolink, or find a suitable replacement attribute to use that is already in Biolink.

**Comment by edgargaticaCU** [comment]
As of last week, the edge attribute has been added to biolink.
https://github.com/biolink/biolink-model/commit/7299b9fd5472905a30e601ff0fb0009dec0a7112

**Comment by edgargaticaCU** [comment]
Per [a discussion on Slack](https://ncatstranslator.slack.com/archives/C014B3JAX36/p1691093022442239) the semmed_agreement_count edge has been removed from the KGX data until after the relay.
